/**
 * @fileoverview gRPC-Web generated client stub for chatPackage
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.15.8
// source: proto/chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_chat_pb from '../proto/chat_pb';
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';


export class ChatClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/chatPackage.Chat/Register',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.RegisterRequest,
    proto_chat_pb.RegisterResponse,
    (request: proto_chat_pb.RegisterRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.RegisterResponse.deserializeBinary
  );

  register(
    request: proto_chat_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_chat_pb.RegisterResponse>;

  register(
    request: proto_chat_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_chat_pb.RegisterResponse) => void): grpcWeb.ClientReadableStream<proto_chat_pb.RegisterResponse>;

  register(
    request: proto_chat_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_chat_pb.RegisterResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatPackage.Chat/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatPackage.Chat/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorChatInitiate = new grpcWeb.MethodDescriptor(
    '/chatPackage.Chat/ChatInitiate',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.InitiateRequest,
    proto_chat_pb.InitiateResponse,
    (request: proto_chat_pb.InitiateRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.InitiateResponse.deserializeBinary
  );

  chatInitiate(
    request: proto_chat_pb.InitiateRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_chat_pb.InitiateResponse>;

  chatInitiate(
    request: proto_chat_pb.InitiateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_chat_pb.InitiateResponse) => void): grpcWeb.ClientReadableStream<proto_chat_pb.InitiateResponse>;

  chatInitiate(
    request: proto_chat_pb.InitiateRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_chat_pb.InitiateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatPackage.Chat/ChatInitiate',
        request,
        metadata || {},
        this.methodDescriptorChatInitiate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatPackage.Chat/ChatInitiate',
    request,
    metadata || {},
    this.methodDescriptorChatInitiate);
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chatPackage.Chat/SendMessage',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.MessageRequest,
    google_protobuf_empty_pb.Empty,
    (request: proto_chat_pb.MessageRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  sendMessage(
    request: proto_chat_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  sendMessage(
    request: proto_chat_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  sendMessage(
    request: proto_chat_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatPackage.Chat/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatPackage.Chat/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorcreateRoom = new grpcWeb.MethodDescriptor(
    '/chatPackage.Chat/createRoom',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.RoomRequest,
    proto_chat_pb.RoomResponse,
    (request: proto_chat_pb.RoomRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.RoomResponse.deserializeBinary
  );

  createRoom(
    request: proto_chat_pb.RoomRequest,
    metadata: grpcWeb.Metadata | null): Promise<proto_chat_pb.RoomResponse>;

  createRoom(
    request: proto_chat_pb.RoomRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_chat_pb.RoomResponse) => void): grpcWeb.ClientReadableStream<proto_chat_pb.RoomResponse>;

  createRoom(
    request: proto_chat_pb.RoomRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_chat_pb.RoomResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatPackage.Chat/createRoom',
        request,
        metadata || {},
        this.methodDescriptorcreateRoom,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatPackage.Chat/createRoom',
    request,
    metadata || {},
    this.methodDescriptorcreateRoom);
  }

  methodDescriptorRoomStream = new grpcWeb.MethodDescriptor(
    '/chatPackage.Chat/RoomStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_chat_pb.RoomStreamRequest,
    proto_chat_pb.RoomStreamResponse,
    (request: proto_chat_pb.RoomStreamRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.RoomStreamResponse.deserializeBinary
  );

  roomStream(
    request: proto_chat_pb.RoomStreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_chat_pb.RoomStreamResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatPackage.Chat/RoomStream',
      request,
      metadata || {},
      this.methodDescriptorRoomStream);
  }

  methodDescriptorUserStream = new grpcWeb.MethodDescriptor(
    '/chatPackage.Chat/UserStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_chat_pb.StreamRequest,
    proto_chat_pb.UserStreamResponse,
    (request: proto_chat_pb.StreamRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.UserStreamResponse.deserializeBinary
  );

  userStream(
    request: proto_chat_pb.StreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_chat_pb.UserStreamResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatPackage.Chat/UserStream',
      request,
      metadata || {},
      this.methodDescriptorUserStream);
  }

  methodDescriptorAllUserStream = new grpcWeb.MethodDescriptor(
    '/chatPackage.Chat/AllUserStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_chat_pb.AllUserRequest,
    proto_chat_pb.UserStreamResponse,
    (request: proto_chat_pb.AllUserRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.UserStreamResponse.deserializeBinary
  );

  allUserStream(
    request: proto_chat_pb.AllUserRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_chat_pb.UserStreamResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatPackage.Chat/AllUserStream',
      request,
      metadata || {},
      this.methodDescriptorAllUserStream);
  }

  methodDescriptorChatStream = new grpcWeb.MethodDescriptor(
    '/chatPackage.Chat/ChatStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_chat_pb.StreamRequest,
    proto_chat_pb.StreamMessage,
    (request: proto_chat_pb.StreamRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.StreamMessage.deserializeBinary
  );

  chatStream(
    request: proto_chat_pb.StreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_chat_pb.StreamMessage> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chatPackage.Chat/ChatStream',
      request,
      metadata || {},
      this.methodDescriptorChatStream);
  }

  methodDescriptorLogOut = new grpcWeb.MethodDescriptor(
    '/chatPackage.Chat/LogOut',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.LogOutRequest,
    google_protobuf_empty_pb.Empty,
    (request: proto_chat_pb.LogOutRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  logOut(
    request: proto_chat_pb.LogOutRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  logOut(
    request: proto_chat_pb.LogOutRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  logOut(
    request: proto_chat_pb.LogOutRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chatPackage.Chat/LogOut',
        request,
        metadata || {},
        this.methodDescriptorLogOut,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chatPackage.Chat/LogOut',
    request,
    metadata || {},
    this.methodDescriptorLogOut);
  }

}

